site_name: My Docs
theme:
 name: material
 logo: assets/logo.png
 features:
    - navigation.sections
 language: fr
extra_css:
 - stylesheets/extra.css
repo_url: https://github.com/ClemsP/OpenRepairPlatform
site_name: OpenRepairPlatform & Réparons
markdown_extensions:
  - admonition
#  - fontawesome_markdown
nav:
  - 'index.md'
  - 'Déploiement': 
      - 'deploiement/installation.md'
      - 'deploiement/first-lauch.md'
  - 'Compte personnel':
      - 'account/create-account.md'
      - 'account/profil.md'
  - 'activity.md'
  - 'location.md'
  - 'Evènements': 
      - 'event/event-index.md'
      - 'event/reservation.md'
      - 'event/create-event.md'
      - 'event/manage-event.md'
  - 'Organisations': 
      - 'organization/org-index.md'
      - 'organization/create.md'
      - 'organization/groups.md'
      - 'organization/members.md'
      - 'organization/manage.md'
  - 'Appareils / objets': 
      - 'stuffs-device/how-it-works.md'
      - 'stuffs-device/inventory.md'
      - 'stuffs-device/view-edit.md'
      - 'stuffs-device/repair.md'
